//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaArlington
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.CuposCliente = new HashSet<CuposCliente>();
            this.Visitas = new HashSet<Visitas>();
        }
    
        public string ClNIt { get; set; }
        public string ClNombresApe { get; set; }
        public string ClDireccion { get; set; }
        public string ClTel { get; set; }
        public string MnIdMunicipio { get; set; }
        public decimal ClCupo { get; set; }
        public Nullable<decimal> ClSaldoCupo { get; set; }
        public Nullable<decimal> ClPorceVisitas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuposCliente> CuposCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visitas> Visitas { get; set; }
    }
}
