//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaArlington
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuposCliente
    {
        public int CcSec { get; set; }
        public string CcClNit { get; set; }
        public decimal CcValor { get; set; }
        public System.DateTime CcFecha { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
