//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaArlington
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitas
    {
        public int VsSec { get; set; }
        public System.DateTime VsFeha { get; set; }
        public decimal VsValorNeto { get; set; }
        public decimal VsValorVisita { get; set; }
        public string VsObservacion { get; set; }
        public string ClNit { get; set; }
        public long VdDocumento { get; set; }
        public string VsIdMuni { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
